language: objective-c
osx_image: xcode10.2

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ReactiveReSwift"
    - UPDATE_DOCS="false"

matrix:
  include:
    - env: SCHEME="macOS"  SDK="macosx10.14"          DESTINATION="arch=x86_64"
    - env: SCHEME="iOS"    SDK="iphonesimulator12.2"  DESTINATION="OS=12.2,name=iPhone X" UPDATE_DOCS="true"
    - env: SCHEME="tvOS"   SDK="appletvsimulator12.2"  DESTINATION="OS=12.2,name=Apple TV 4K"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages
